---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install MySQL {{ mysql_version }} on Ubuntu
  apt:
    name: "{{ ubuntu_packages }}"
    state: present

- name: Ensure MySQL is started and enabled
  service:
    name: mysql
    state: started
    enabled: yes


- name: Set MySQL root password and auth method
  mysql_user:
    name: root
    host: localhost
    password: "{{ mysql_root_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    check_implicit_admin: yes
    priv: "*.*:ALL,GRANT"
    plugin: mysql_native_password
  become: yes
  no_log: false


- name: Create MySQL database
  community.mysql.mysql_db:
    name: "{{ mysql_database }}"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"
    

- name: Create multiple MySQL users
  community.mysql.mysql_user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    host: "%"
    priv: "{{ item.priv }}"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"
  loop: "{{ mysql_users }}"




- name: Copy MySQL config from template
  template:
    src: conf.j2
    dest: "/etc/mysql/my.cnf"
    owner: root
    group: root
    mode: 0644
  notify: Restart MySQL
